# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # (1..3).each do |i|
  (1..3).each do |i|

    vm_name = "swarm0#{i}"

    config.vm.define vm_name do |s|

      # hostname
      s.vm.hostname = vm_name
      # os
      s.vm.box = "ubuntu/focal64"
      # network
      private_ip = "192.168.10.#{i+30}"
      s.vm.network "private_network", ip: private_ip

      # spec
      s.vm.provider "virtualbox" do |v|
        v.gui = false        
        v.cpus = 1
        v.memory = 1024
      end

      # Common
      s.vm.provision :shell, :path => "./shell/common.sh"

      if i == 1 then
        # Manager
        s.vm.provision :shell, :path => "./shell/manager.sh"
      else
        # Worker
        s.vm.provision :shell, :path => "./shell/worker.sh"
      end

      # post process
      s.vm.provision :shell, :path => "./shell/postprocess.sh"

    end
  end
end