# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # (1..3).each do |i|
  (1..3).each do |i|

    if i == 1 then
      vm_name = "master"
    else
      vm_name = "worker0#{i-1}"
    end

    config.vm.define vm_name do |s|

      # hostname
      s.vm.hostname = vm_name
      # os
      s.vm.box = "ubuntu/focal64"
      # network
      private_ip = "192.168.10.#{i+20}"
      s.vm.network "private_network", ip: private_ip

      # spec
      s.vm.provider "virtualbox" do |v|
        v.gui = false        
        if i == 1 then
          v.cpus = 2
          v.memory = 2048
        else
          v.cpus = 1
          v.memory = 1024
        end
      end

      # Common
      s.vm.provision :shell, :path => "./shell/common.sh"

      if i == 1 then
        # Master
        s.vm.provision :shell, :path => "./shell/master.sh"
      else
        # Worker
        s.vm.provision :shell, :path => "./shell/worker.sh"
      end

      # post process
      s.vm.provision :shell, :path => "./shell/postprocess.sh"

    end
  end
end