version: "3.9"

services:
  splunk:
    hostname: splunk
    container_name: splunk
    build:
      context: ./splunk
      dockerfile: Dockerfile
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
    ports:
      - 8000:80
