"""
This type stub file was generated by pyright.
"""

from ._common import *
from . import _common, common, doccer
from scipy._lib._testutils import PytestTester

"""
==========================================
Miscellaneous routines (:mod:`scipy.misc`)
==========================================

.. currentmodule:: scipy.misc

Various utilities that don't have another home.

.. autosummary::
   :toctree: generated/

   ascent - Get example image for processing
   central_diff_weights - Weights for an n-point central mth derivative
   derivative - Find the nth derivative of a function at a point
   face - Get example image for processing
   electrocardiogram - Load an example of a 1-D signal.

"""
__all__ = _common.__all__
test = ...
