"""
This type stub file was generated by pyright.
"""

__all__ = ['central_diff_weights', 'derivative', 'ascent', 'face', 'electrocardiogram', 'arange', 'newaxis', 'hstack', 'prod', 'array', 'load']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

