version: "3.9"

services:
  api:
    container_name: api-dev
    hostname: api-dev
    restart: always
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    expose:
      - 80
    volumes:
      - ./api/app/app:/app/app
    networks:
      - web
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=fastapi
    labels:
      - traefik.enable=true
      - traefik.http.routers.env-fastapi.entrypoints=web
      - traefik.http.routers.env-fastapi.rule=PathPrefix(`/env-fastapi`)
      - traefik.http.routers.env-fastapi.middlewares=strip-prefix-env-fastapi
      - traefik.http.middlewares.strip-prefix-env-fastapi.stripprefixregex.regex=/env-fastapi
    depends_on:
      - db

  db:
    container_name: db
    hostname: db
    restart: always
    tty: true
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data/
    networks:
      - web
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi

networks:
  web:
    name: docker-mgr_web
    external: true
