version: "3.9"

services:
  api:
    container_name: api-dev
    hostname: api-dev
    restart: always
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    expose:
      - 80
    volumes:
      - ./api/app/app:/app/app
      - ./api/tests:/app/tests
    networks:
      - web
    environment:
      - DB_USER=fastapi
      - DB_PASSWORD=fastapi
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=fastapi
    labels:
      - traefik.enable=true
      - traefik.http.routers.env-fastapi.entrypoints=web
      - traefik.http.routers.env-fastapi.rule=PathPrefix(`/env-fastapi`)
      - traefik.http.routers.env-fastapi.middlewares=strip-prefix-env-fastapi
      - traefik.http.middlewares.strip-prefix-env-fastapi.stripprefixregex.regex=/env-fastapi
    depends_on:
      - db

  db:
    container_name: db
    hostname: db
    restart: always
    tty: true
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - web
    environment:
      - MYSQL_USER=fastapi
      - MYSQL_PASSWORD=fastapi
      - MYSQL_DATABASE=fastapi
    command: --default-authentication-plugin=mysql_native_password

networks:
  web:
    name: docker-mgr_web
    external: true
