"""
This type stub file was generated by pyright.
"""

__all__ = ['mminfo', 'mmread', 'mmwrite', 'MMFile', 'coo_matrix', 'isspmatrix', 'asstr']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

