version: "3.7"

services:
  dind:
    build:
      context: .
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    container_name: dind
    hostname: dind
    privileged: true
    ports:
      - "2222:22"
      - "6000-6010:6000-6010"
