"""
This type stub file was generated by pyright.
"""

__all__ = ['spline_filter', 'bspline', 'gauss_spline', 'cubic', 'quadratic', 'cspline1d', 'qspline1d', 'cspline1d_eval', 'qspline1d_eval', 'logical_and', 'zeros_like', 'piecewise', 'array', 'arctan2', 'tan', 'arange', 'floor', 'exp', 'greater', 'less', 'add', 'less_equal', 'greater_equal', 'cspline2d', 'sepfir2d', 'comb', 'float_factorial']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

