"""
This type stub file was generated by pyright.
"""

__all__ = ['lti', 'dlti', 'TransferFunction', 'ZerosPolesGain', 'StateSpace', 'lsim', 'lsim2', 'impulse', 'impulse2', 'step', 'step2', 'bode', 'freqresp', 'place_poles', 'dlsim', 'dstep', 'dimpulse', 'dfreqresp', 'dbode', 's_qr', 'integrate', 'interpolate', 'linalg', 'interp1d', 'tf2zpk', 'zpk2tf', 'normalize', 'freqs', 'freqz', 'freqs_zpk', 'freqz_zpk', 'tf2ss', 'abcd_normalize', 'ss2tf', 'zpk2ss', 'ss2zpk', 'cont2discrete', 'atleast_1d', 'atleast_2d', 'squeeze', 'transpose', 'zeros_like', 'linspace', 'nan_to_num', 'LinearTimeInvariant', 'TransferFunctionContinuous', 'TransferFunctionDiscrete', 'ZerosPolesGainContinuous', 'ZerosPolesGainDiscrete', 'StateSpaceContinuous', 'StateSpaceDiscrete', 'Bunch']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

