FROM python:3.9-buster

# package
RUN apt update -y && \
    apt upgrade -y && \
    apt install -y git 
RUN pip install --upgrade pip && \
    pip install poetry

# poetry
# RUN poetry new app
WORKDIR /app
# RUN poetry config --local virtualenvs.path ".venv" && \
#     poetry config --local virtualenvs.in-project true 
# RUN poetry add fastapi sqlalchemy psycopg2 uvicorn gunicorn flake8 black 
COPY ./poetry.toml ./poetry.toml
COPY ./pyproject.toml ./pyproject.toml 
RUN poetry install
# app
COPY ./app/app /app/app

CMD ["poetry", "run", "uvicorn", "--host", "0.0.0.0", "--port", "80", "--reload", "--log-level", "warning", "app.main:app"]