"""
This type stub file was generated by pyright.
"""

from scipy.stats._boost.beta_ufunc import _beta_cdf, _beta_isf, _beta_kurtosis_excess, _beta_mean, _beta_pdf, _beta_ppf, _beta_sf, _beta_skewness, _beta_variance
from scipy.stats._boost.binom_ufunc import _binom_cdf, _binom_isf, _binom_kurtosis_excess, _binom_mean, _binom_pdf, _binom_ppf, _binom_sf, _binom_skewness, _binom_variance
from scipy.stats._boost.nbinom_ufunc import _nbinom_cdf, _nbinom_isf, _nbinom_kurtosis_excess, _nbinom_mean, _nbinom_pdf, _nbinom_ppf, _nbinom_sf, _nbinom_skewness, _nbinom_variance
from scipy.stats._boost.hypergeom_ufunc import _hypergeom_cdf, _hypergeom_isf, _hypergeom_kurtosis_excess, _hypergeom_mean, _hypergeom_pdf, _hypergeom_ppf, _hypergeom_sf, _hypergeom_skewness, _hypergeom_variance
from scipy.stats._boost.ncf_ufunc import _ncf_cdf, _ncf_isf, _ncf_kurtosis_excess, _ncf_mean, _ncf_pdf, _ncf_ppf, _ncf_sf, _ncf_skewness, _ncf_variance

